<?php

/**
* @copyright Copyright (c) Metaways Infosystems GmbH, 2011
* @license LGPLv3, http://www.arcavias.com/en/license
* @version $Id: layout.phtml 1375 2012-11-01 15:36:56Z nsendetzky $
*/

$time = microtime( true );
$searchString = (isset( $this->params['f-search-text'] ) ) ? htmlspecialchars( $this->params['f-search-text'] ) : '';
$sites = $this->sites();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.5" />
		<title>Arcavias</title>
		<link href="<?php echo $this->pathstart;?>/styles/main.css" type="text/css" rel="stylesheet" media="screen" />
		<link href="<?php echo $this->pathstart;?>/styles/arcavias.css" type="text/css" rel="stylesheet" media="screen" />
		<link href="<?php echo $this->pathstart;?>/styles/search.css" type="text/css" rel="stylesheet" media="screen" />
		<!--[if lt IE 8]>
			<link href="<?php echo $this->pathstart;?>/styles/ie.css" type="text/css" rel="stylesheet" />
		<![endif]-->
		<script type="text/javascript" src="<?php echo $this->pathstart;?>/js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo $this->pathstart;?>/js/jquery-ui-1.10.0.custom.min.js"></script>
		<?php echo ( isset( $this->filter ) ? $this->filter->getHeader() : '' ); ?>
		<?php echo ( isset( $this->searchfilter ) ? $this->searchfilter->getHeader() : '' ); ?>
		<?php echo ( isset( $this->list ) ? $this->list->getHeader() : '' ); ?>
		<?php echo ( isset( $this->detail ) ? $this->detail->getHeader() : '' ); ?>
		<?php echo ( isset( $this->basket ) ? $this->basket->getHeader() : '' ); ?>
		<?php echo ( isset( $this->minibasket ) ? $this->minibasket->getHeader() : '' ); ?>
		<?php echo ( isset( $this->checkout ) ? $this->checkout->getHeader() : '' ); ?>
		<?php echo ( isset( $this->confirm ) ? $this->confirm->getHeader() : '' ); ?>
	</head>
	<body>
		<div id="frame">
			<div id="main">
				<div id="mainBg" class="clearfix">
					<div id="headerImg">
						<div id="header">
							<div id="headerLogo">
								<a href="<?php echo $this->url( array( 'site' => $this->params['site'] ), 'routeMin', true ); ?>">
									<img src="<?php echo $this->pathstart;?>/images/arcavias.gif" alt="Arcavias" />
								</a>
							</div>
							<div id="headerMiddle">
								<div id="headerNavigation">
									<?php
									foreach($sites as $code => $label) {
										echo '<a href="' . $this->url( array( 'site' => $code ), 'routeMin', true ) . '">' . $label . '</a>';
									}
									?>
								</div>
								<div id="headerSearch">
									<?php if( isset( $this->searchfilter ) ) : ?>
									<?php echo $this->searchfilter->getBody(); ?>
									<?php endif; ?>
								</div>
							</div>
							<div id="headerBasket" align="center">
								<?php
								if( isset( $this->minibasket ) ) {
									echo $this->minibasket->getBody();
								}
								?>
							</div>
						</div>
						<div id="navigation" class="clearfix">
							<div id="navigationMenue">
								<?php
								foreach($this->category() AS $item) {
									echo '<a href="' . $item['uri'] . '" class="' . $item['class'] . '">' . htmlspecialchars( $item['label'] ) . '</a>' . PHP_EOL;
								};
								?>
							</div>
						</div>
						<div id="spacer">&nbsp;</div>
						<div id="content" class="clearfix">
							<?php if( isset( $this->filter ) ) : ?>
							<div id="contentLeft">
								<?php echo $this->filter->getBody(); ?>
							</div>
							<?php else : ?>
							<?php endif; ?>
							<div id="contentRight">
								<?php echo $this->layout()->content; ?>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="footer">
				<div id="footerTop" class="clearfix">
					<div id="footerTopLeft"></div>
					<div id="footerTopRight"></div>
				</div>
				<div id="footerBottom">
					Layout courtesy to <a href="http://www.kauscheundpartner.de/">Kausche&amp;Partner</a>
				</div>
			</div>
		</div>
	</body>
</html>